/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        display: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
      },
      colors: {
        ck: {
          red: '#e11d48',
          'red-hover': '#be123c',
          bg: '#101114',
          surface: '#16171b',
          'surface-2': '#1c1e23',
          'surface-3': '#232830',
          border: '#26272c',
          'border-2': '#2b2d33',
          divider: '#202127',
          text: '#f4f4f5',
          'text-2': '#e4e4e7',
          'text-3': '#a1a1aa',
          'text-muted': '#71717a',
          'text-faint': '#52525b',
          green: '#34d399',
          'green-bg': '#1a2e24',
          'red-bg': '#2b1a1e',
          'red-border': '#4c2028',
          'red-text': '#fca5a5',
          amber: '#fbbf24',
          'amber-bg': '#2e2618',
          blue: '#60a5fa',
          'blue-bg': '#1e2a3d',
          purple: '#a78bfa',
          // Legacy aliases
          dark: '#101114',
          'dark-card': '#16171b',
          'dark-border': '#26272c',
          'dark-surface': '#1c1e23',
          muted: '#a1a1aa',
          'muted-light': '#e4e4e7',
        },
      },
    },
  },
  plugins: [],
};
