/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        display: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        barlow: ['Barlow', 'system-ui', 'sans-serif'],
        heading: ['Barlow Condensed', 'Barlow', 'system-ui', 'sans-serif'],
      },
      colors: {
        ck: {
          red: 'var(--ck-accent, #e11d48)',
          'red-hover': 'var(--ck-accent-hover, #be123c)',
          bg: 'var(--ck-bg, #101114)',
          surface: 'var(--ck-surface, #16171b)',
          'surface-2': 'var(--ck-surface-2, #1c1e23)',
          'surface-3': 'var(--ck-surface-3, #232830)',
          border: 'var(--ck-border, #26272c)',
          'border-2': 'var(--ck-border-2, #2b2d33)',
          divider: '#202127',
          text: 'var(--ck-text, #f4f4f5)',
          'text-2': 'var(--ck-text-2, #e4e4e7)',
          'text-3': 'var(--ck-text-3, #a1a1aa)',
          'text-muted': 'var(--ck-text-muted, #71717a)',
          'text-faint': 'var(--ck-text-faint, #52525b)',
          'icon-bg': 'var(--ck-icon-bg, #ffffff)',
          'icon-fg': 'var(--ck-icon-fg, #101114)',
          green: '#34d399',
          'green-bg': '#1a2e24',
          'red-bg': '#2b1a1e',
          'red-border': '#4c2028',
          'red-text': '#fca5a5',
          amber: '#fbbf24',
          'amber-bg': '#2e2618',
          blue: '#60a5fa',
          'blue-bg': '#1e2a3d',
          purple: '#a78bfa',
          // Legacy aliases — also driven by CSS vars
          dark: 'var(--ck-bg, #101114)',
          'dark-card': 'var(--ck-surface, #16171b)',
          'dark-border': 'var(--ck-border, #26272c)',
          'dark-surface': 'var(--ck-surface-2, #1c1e23)',
          muted: 'var(--ck-text-3, #a1a1aa)',
          'muted-light': 'var(--ck-text-2, #e4e4e7)',
        },
      },
    },
  },
  plugins: [],
};
